#
# Module manifest for module 'KnownFolders'
#
# Generated by: Jakub Bereżański
#
# Generated on: 2013-11-02
#

@{

# Script module or binary module file associated with this manifest.
#RootModule = ''
ModuleToProcess = 'BlaSoft.PowerShell.KnownFolders.dll'

# Version number of this module.
ModuleVersion = '1.1.0'

# ID used to uniquely identify this module
GUID = '0147f508-4b23-40d4-9769-03440807891f'

# Author of this module
Author = 'Jakub Bereżański'

# Company or vendor of this module
CompanyName = 'BlaSoft'

# Copyright statement for this module
Copyright = '(c) 2013 Jakub Bereżański. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A set of cmdlets to manipulate the Known Folders of the Windows Shell.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '3.5'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '2.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 
               'BlaSoft.PowerShell.KnownFolders.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('KnownFolders.format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @()

# Cmdlets to export from this module
CmdletsToExport = @(
    'Get-KnownFolder'
    'Move-KnownFolder'
)

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 
               'BlaSoft.PowerShell.KnownFolders.dll'

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

